version: '3'

services:

  vladi_app:
    build:
      context: vladi_app
    volumes:
      - app_log:/app
      - ./vladi_app/demo.py:/app/demo.py

  filebeat:
    hostname: filebeat
    user: root #To read the docker socket
    image: docker.elastic.co/beats/filebeat:7.1.1
    volumes:
      #Mount the Filebeat configuration so users can make edits.
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      #Mount the vladi_app system log directory.
      - app_log:/var/log:ro
    command: filebeat -e -strict.perms=false
    links:
      - logstash


  logstash:
    hostname: logstash 
    image: docker.elastic.co/logstash/logstash:7.1.1
    ports:
      - 5044:5044
    volumes:
      - ./logstash/pipeline/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml
    links:
      - elasticsearch

  elasticsearch:
    hostname: elasticsearch
    build:
      context: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-logs-elk-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
#      - ./elasticsearch/data:/usr/share/elasticsearch/data # if you don't want to loose data on every docker down
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.1.1
    environment:
      - "LOGGING_QUIET=true"
    links:
      - elasticsearch
    ports:
      - 5601:5601


volumes:
  app_log:
